### ISSUE TITLE
模型排行榜得分计算规则

### ISSUE THREAD

**Issue by lixiaochuan2020** [JimmyyyChen/modeleval#22]
### 客观题

我们规定：

1. 每个模型有一个全局变量`score_obj`，存储该模型在迄今为止所有的客观测试上测试的得分。设模型$`M`$共进行了$`N`$轮测试任务，每次测试任务使用的数据集为$`D_i`$；数据集$`D_i`$内共包含$`A_i`$条数据，模型在数据集$`D_i`$上共回答正确了$`a_i`$道题目，则该模型的全局客观得分为：
   $$ScoreObj_{M} = \frac{1}{N}\sum_{i=1}^{N}\frac{a_i}{A_i}$$

3. 此外，我们也为每个`模型-数据集`存储一个单独的得分变量`score_obj_on_dataset`，以便用户单独获取某个模型在某个数据集上的得分。其计算规则为：
   $$ScoreObjOnDataset_i = \frac{a_i}{A_i}$$

### 主观题

同客观题。`score_sub`用于存储模型在迄今为止所有的主观测试上测试的得分；`score_sub_on_dataset`用于存储模型在单个数据集上的得分。

### 对抗性评测

在对抗评测中，模型$`M`$的得分$`S`$这一变量由三个因素共同影响：模型$`M`$、被比较的模型$`M^{'}`$、对抗性评测使用的数据集$`D`$。我们假设模型$`M`$和$`j`$个其他模型在$`k`$个数据集上进行过对抗性评测
$$ScoreAd(M, M_j,D_k) = \frac{\sum_k\sum_j\times S(M,j,k)}{Num}$$

- $`S(M,j,k)`$代表模型$`M`$在数据集$`D_k`$上和模型$`M_j`$进行对抗性评测的得分。在对抗性评测中，如果用户判定模型$`M_i`$比$`M_j`$的回答要更好，则$`M_i`$得1分，$`M_j`$得0分。设数据集$`D_k`$中有$`N`$条数据，模型$`M`$在其中$`n`$条数据上比模型$`M_j`$回答更好，则：
$$S(M,j,k) = \frac{n}{N}$$

- $`Num = \sum_k\sum_jI(M,j,k)`$。
  $`I(M,j,k)`$为示性函数，若模型$`M`$与$`M_j`$在数据集$`D_j`$上进行过对抗性研究，则$`I(M,j,k)=1`$，否则为$`0`$。

以上所有计算结果最终均将转换为百分比，并去掉百分号作为模型得分（理论满分为100分）。

@JimmyyyChen @ZhangZhiyuan-2021 @molamola-msc 请共同讨论上述方案是否合理。

**Comment by JimmyyyChen** [comment]
Nice
